### ISSUE TITLE
Wrong path for liquid posts

### ISSUE THREAD

**Issue by thowenzel** [cobalt-org/cobalt.rs#216] opened 2017-05-05 10:55 UTC
First at all: I'm not sure if its a problem with cobalt.rs, with liquid-rust or just my mistake or misunderstanding.

If your see [my page](https://thowenzel.github.io/), you can see on the main page the articles (the page is not finished yet, so please do not be too critical). By clicking on the title the article is opened. As href is use `{{ post.path }}`. Same for the sidebar on the mainpage. 
Everything works fine.

But if you opoen the [About](https://thowenzel.github.io/about/) section, the link in the sidebar is changed.

For example:
On mainpage the link is `https://thowenzel.github.io/2017/rust-using-vscode.html`.
On the About page the link is `https://thowenzel.github.io/about/2017/rust-using-vscode.html`

So ther is the folder `about` added to the path. But in both cases I used `{{ post.path }}` because it should give the absolute path. 

The sourcecode for my page can be found [here](https://github.com/thowenzel/thowenzel.github.io).

Some ideas?

**Comment by epage** [comment] 2017-05-05 13:49
Thanks for letting us know about this.  I suspect the issue is in cobalt.

Looking in your liquid files, I suspect the problem is that we aren't inserting a leading "/" in your path, making it relative.  So this should be fairly easy to work around.

For example on https://raw.githubusercontent.com/thowenzel/thowenzel.github.io/source/posts/2017-quotes-february.md

Change
`path: 2017/quotes-february.html`
to
`path: /2017/quotes-february.html`

**Comment by Svenito** [comment] 2017-05-10 11:21
It actually seems that it's not forgotten, but actively removed [here](https://github.com/cobalt-org/cobalt.rs/blob/5aa5813479c00683e321def73a8b2e6cbc14fa9e/src/document.rs#L94)

Another workaround however, which IMO is simpler, is to prefix the `{{ post.path }}` with a `/` in the template.

**Comment by thowenzel** [comment] 2017-05-15 13:11
Sorry for my late reply. 
Thanks for your help. But I'm not sure if I have my "problem" correctly expressed:

For example, see the mainpage `https://thowenzel.github.io/` and the About page `https://thowenzel.github.io/about/`. In both cases your find on the right side a column called **Neueste Beiträge** (newest articles). If your try to open the first article **Rust und Visual Studio Code**, in case of main page the article opens, in case of about page the article could not find.

My website is not finished, so the right column is not viewable on mobile devices.

The link is in both cases set as 
`<a href="{{ post.path }}">{{ post.title }}</a>`

I think this should be the absolute path. But cobalt generates different links:
On the main page:
`https://thowenzel.github.io/2017/rust-using-vscode.html` (thats the correct path)
On the about page:
`https://thowenzel.github.io**/about**/2017/rust-using-vscode.html` (the **about** is wrong here).
So for me it looks like `{{ post.path }}` gives me only a relative path.

I tried your workaround but I think the "/" is not the problem, btw. not the solution for my problem.

**Comment by epage** [comment] 2017-05-16 01:26
Wow, that is pretty busted.  I expect I'll have some time tomorrow night to look into it.

**Comment by epage** [comment] 2017-05-17 00:25
Have you re-generated your site since commit 63b1a359dc7267adb8b102d36de5fc3a1b330398?

I did a build of your site and Svenito's workaround of `/{{ post.path }}`  seems to work.  If the workaround is good enough, I'll hold off looking into this while I fix some other issues.

**Comment by thowenzel** [comment] 2017-05-22 14:06
Yes, I re-generated my page, but the issue is still existing. But I will investigate this more closely tomorrow.

**Comment by Svenito** [comment] 2017-05-24 16:45
I just rebuilt your site as well with the latest master build of cobalt, and am not seeing the issue either. I go from the `2017/rust-using-vscode.html` url to `about` with no problem

**Comment by thowenzel** [comment] 2017-06-09 06:41
Thaks for your feedback. I will try it again next weekend.

**Comment by thowenzel** [comment] 2017-07-10 12:06
So, a bit late but now I had time and have tested the solution. I have regenereted my site after installing the latest version of cobalt. Now it works fine for me.

**Comment by epage** [comment] 2017-07-12 00:01
So the way forward for this.

So not all sites are at the root directory.  For example, Hugo offers a [`Site.BaseURL` variable](https://gohugo.io/templates/variables/) that you use to concatenate with the `Page.URL` (I think).  I'm unsure if they use a leading `/`.  Jekyll always uses a leading `/` and the user needs to create or hardcode a base URL, if needed.  Either way, ideally, the base url is something that can be overridden for `cobalt serve`.

**Action items for this issue**
- At minimum, we should add a global base url that can be overriden at the command prompt.
- The question is then whether the `page.path` should have a leading `/` or not.

For leading `/`
- "just works" when the site is at the root
- This is what jekyll does

For no leading `/`
- `{{ base }}/{{ page.path}}` looks nicer than `{{ base }}{{ page.path}}`

Any opinions on this?

**Comment by epage** [comment] 2017-10-21 00:36
We have a config option, link, that serves the same purpose.  Currently its only used for rss/jsonfeed but #171 is about exposing these.

I think I'd like to rename it to base url while at it (see #199 for config format discussions)

**Comment by epage** [comment] 2017-10-22 03:05
FYI I'm leaning the route of:
- `site.base_url` will not have a trailing slash
- `page.path` will not have a leading slash

To allow for `{{site.base_url}}/{{page.path}}`

**Comment by epage** [comment] 2017-10-26 14:41
Fixed by #311

**Closed by epage** 2017-10-26 14:41 UTC
Labels: bug

**Comment by thowenzel** [comment] 2017-11-03 09:19
Thanks, good work.
