### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by LucioFranco** [cobalt-org/cobalt.rs#103] opened 2016-05-11 16:30 UTC
It would be cool to have a themes folder where people would have different layout files. That way they could pass a command or env variable to tell cobalt which theme to compile the site with.

**Comment by flosse** [comment] 2016-05-12 22:48
Actually one thing I really like is to **not** having themes ;-) I like it simple.
But maybe there is an elegant way to do it!?

**Comment by LucioFranco** [comment] 2016-06-15 14:17
I was thinking of having theme folders inside the layouts folder. When you selected what theme you wanted it would use the files inside theme folder and merge them with the layout folder file. Or should a theme just be different css files?

**Comment by Geobert** [comment] 2018-01-02 15:44
@epage: is this a duplicate of #301 ?

**Comment by epage** [comment] 2018-01-02 16:04
You're right, I missed that this was here.  While this was first, #301 has more details, closing this.

**Closed by epage** 2018-01-02 16:04 UTC
Labels: enhancement
