### ISSUE TITLE
cobalt serve should ignore changes in destination dir

### ISSUE THREAD

**Issue by fabrixxm** [cobalt-org/cobalt.rs#833] opened 2021-02-17 10:55 UTC
looks like `cobalt serve` is watching the destination dir for changes, so a rebuild trigger a rebuild resulting in a loop of rebuilds:

```
$ cobalt serve -d public
[info] Building from "██████" into "public"
[info] Watching "██████" for changes
[info] Serving "public" through static file server
[info] Server Listening on http://localhost:3000
[info] Ctrl-c to stop the server
[info] Watching "██████" for changes
[info] Building from "██████" into "public"
[info] Building from "██████" into "public"
[info] Building from "██████" into "public"
[info] Building from "██████" into "public"
[info] Building from "██████" into "public"
...
````

**Comment by epage** [comment] 2021-02-22 15:37
Yes, this is a bug that we should be fixing

**Comment by rdimartino** [comment] 2022-08-26 20:40
Fairly certain this was fixed in https://github.com/cobalt-org/cobalt.rs/releases/tag/v0.16.5 by https://github.com/cobalt-org/cobalt.rs/pull/855

I can recreate the issue issue v0.16.4, but not v0.16.5

(https://github.com/cobalt-org/cobalt.rs/pull/916 seems also related, but I couldn't reproduce this specific issue with any later releases)

**Closed** 2022-08-26 20:47 UTC
Labels: bug
