### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by achernyak** [cobalt-org/cobalt.rs#90] opened 2016-04-26 12:48 UTC
I believe #88 caused tests to start failing because of how the documents are being condensed with the new type.
```
failures:
    copy_files
    custom_template_extensions
    dotfiles
    example
    rss
    sort_posts
```

**Comment by johannhof** [comment] 2016-04-27 16:36
They're not failing on Travis, what's the error you are getting?

**Comment by achernyak** [comment] 2016-05-08 23:18
So I ran the tests on a few platforms and appears to be  windows specific issue. It seems the escape character encoding on windows causes the test to fail. I don't think this is something we can fix and would just need to add a note about.

The gist of the error is below, including all the tests which are failing.

```

---- copy_files stdout ----
        <!DOCTYPE html>
<html>
    <head>
        <title>My blog - My first Blogpost</title>
    </head>
    <body>
        <h1>My first [91mBlogpost</h1>
<p>Hey[0m [92mBlogpost</h1>
<p>Hey[0m there this is my first blogpost and this is super [91mawesome.</p>
<p>My[0m [92mawesome.</p>
<p>My[0m Blog is lorem ipsum like, yes it [91mis..</p>

   [0m [92mis..</p>

   [0m </body>
</html>


thread 'copy_files' panicked at 'assertion failed: edit distance between "<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>My blog - My first Blogpost</title>\r\n    </head>\r\n    <body>\r\n        <h1>My first Blogpost</h1>\r\n<p>Hey there this is my first blogpost and this is super awesome.</p>\r\n<p>My Blog is lorem ipsum like, yes it is..</p>\r\n\r\n    </body>\r\n</html>\r\n\r\n" and "<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>My blog - My first Blogpost</title>\r\n    </head>\r\n    <body>\r\n        <h1>My first Blogpost</h1>\n<p>Hey there this is my first blogpost and this is super awesome.</p>\n<p>My Blog is lorem ipsum like, yes it is..</p>\n\r\n    </body>\r\n</html>\r\n\r\n" is 6 and not 0, see diffset above', C:\Users\artem\.cargo\registry\src\github.com-88ac128001ac3a9a\difference-0.4.1\src\lib.rs:86


failures:
    copy_files
    custom_template_extensions
    dotfiles
    example
    rss
    sort_posts
```

**Comment by johannhof** [comment] 2016-05-09 05:38
Oh, interesting. I'll look into it, thanks for reporting. :)

**Comment by johannhof** [comment] 2016-07-25 10:34
Can be witnessed on Appveyor https://ci.appveyor.com/project/johannhof/cobalt-rs, I think that it's both about new lines and some backslashes not being converted to forward slashes correctly.

**Comment by johannhof** [comment] 2016-08-08 20:55
Since test on Appveyor are now succeeding I'll close this, although strangely we didn't fix the linebreak issue. Feel free to reopen if anyone can reproduce.

**Closed by johannhof** 2016-08-08 20:55 UTC
Labels: tests, windows
